### ISSUE TITLE
Remove the Jenkins setup wizard

### ISSUE THREAD

**Issue by edinc** [edinc/vagrant-jenkins#1]
On first provisioning of the vagrant box when running the Jenkins server the user has to go through a security setup wizard. This should be removed to further speed up the process of having the Jenkins ready.

**Comment by tony-dunlop** [comment]
I've done this before so might be able to help, it's a case of adding  jenkins xml config files

**Comment by edinc** [comment]
Any contributions are welcome really.

**Comment by edinc** [comment]
This was resolved with #10.
Thank you for all your contributions @munkiepus. I will add you as a collaborator to the repository so that you can directly create branches and review and merge future PR-s.
