### ISSUE TITLE
Unable to properly finish jenkins setup (E: Some packages could not be authenticated)

### ISSUE THREAD

**Issue by chrisdnz** [edinc/vagrant-jenkins#13]
I was trying to setup following the easy cake instructions but Jenkins binary wasn’t able to download into the ubuntu VM. 
This was the errors I got after I dig in.

<img src="https://p43.f3.n0.cdn.getcloudapp.com/items/wbu0YyJe/Image%202020-05-04%20at%209.12.51%20PM.png?v=1894be75c770f9f54d3a93478c244353" alt="error screenshot"></img>

So I get that you missed one step before installing Jenkins and I would love to contribute that fix.

**Comment by edinc** [comment]
@cnajeraz Feel free to submit a PR, I would gladly appreciate it.
