### ISSUE TITLE
jenkins doesnt start because of lack of java

### ISSUE THREAD

**Issue by Solith** [edinc/vagrant-jenkins#4]
- no java installed which causes jenkins service start failure
- cat /var/lib/jenkins/secrets/initialAdminPassword   doesn't exist until jenkins service runs

How I fixed it:

vagrant ssh
sudo apt-get install default-jre
// ...ended in error restarting jenkins for some reason
sudo apt-get purge default-jre
sudo apt-get install default-jre
//  ...now it worked
// need to restart service but it asks for password and all i tried ends in auth failure ...so have to reboot
vagrant halt
vagrant up
sudo cat /var/lib/jenkins/secrets/initialAdminPassword
// now jenkins worked

**Comment by tomasnorre** [comment]
I had the same issue, but installed it per hand, but the same package.

**Comment by edinc** [comment]
Fixed in #6. Closing.
