### ISSUE TITLE
wrong port forward in vagrantfile

### ISSUE THREAD

**Issue by tony-dunlop** [edinc/vagrant-jenkins#8]
should the port forward in vagrantfile not be 8080->8080 rather than 80->8080?

**Comment by edinc** [comment]
Hey @munkiepus. I've set the forwarding to 80 because there also being a `nginx` instance installed in front of Jenkins. So when you add for example `jenkins.local` to you `hosts` file you don't have to type `jenkins.local:8080` in your browsers, you can only type `jenkins.local`.

**Comment by tony-dunlop** [comment]
Ahh, i see, looking at the logs i don't think nginx was installed properly on my instance but it looks network related rather than the vagrant setup, will have a look into it. thanks for getting back to me

**Comment by tony-dunlop** [comment]
Actually, solved the network problem and just looked at it again. 
the sync folder is set to:
`config.vm.synced_folder ".", "/mnt/host_machine"`
and the provision.sh (line 46) script tries to copy the nginx conf from /vagrant/VirtualHost/jenkins
`sudo cp /vagrant/VirtualHost/jenkins /etc/nginx/sites-available/`

changing that to:
`sudo cp /mnt/host_machine/VirtualHost/jenkins /etc/nginx/sites-available/`
solved the problem :)

**Comment by tony-dunlop** [comment]
I have a branch ready to push with the change if you would like me to

**Comment by edinc** [comment]
@munkiepus Please do so, then I'll review it to see the actual code changes :)

**Comment by edinc** [comment]
Closing since it's been fixed in #9.
Thank you!
